# Generated by Django 2.2.2 on 2019-06-08 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='to',
            new_name='destination',
        ),
    ]
