# Generated by Django 2.2.2 on 2019-06-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20190608_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(default='Wakanda', max_length=100),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
