# Generated by Django 2.2.2 on 2019-06-23 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_auto_20190608_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='miles',
        ),
    ]
