# Generated by Django 2.2.2 on 2019-06-23 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_remove_booking_miles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='number_of_travellers',
            new_name='passengers',
        ),
    ]
